services:
  ubuntu:
    image: dorowu/ubuntu-desktop-lxde-vnc
    container_name: ubuntu
    ports:
      - "6080:80"     # browser access
      - "5600:5600"   # VNC access
    environment:
      RESOLUTION: "1280x800"
      VNC_PASSWORD: "ajith"
    volumes:
      - ubuntu_data:/home/ubuntu
    restart: unless-stopped

volumes:
  ubuntu_data:
    driver: local
